name: Package Reduced Diagnostic Data Language Pack

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package application
        run: |
          pip install pyinstaller
          pyinstaller --noconfirm --onefile --windowed --icon "src/VW.ico" "src/Reduced-Diagnostic-Data-Language-Pack.py"

      - name: Upload packaged application
        uses: actions/upload-artifact@v4
        with:
          name: Reduced-Diagnostic-Data-Language-Pack.exe
          path: dist/Reduced-Diagnostic-Data-Language-Pack.exe
